%YAML 1.1
---
targets:
  - name: ROOM1
    directory: 'D:\Record'
	fileDateFormat: 'yyyyMMdd'
	cameraNameRegex: '^[0-9]{4}$'

  - name: ROOM2
    directory: 'E:\CFTV\Record'

fileList:
  directory: 'D:\Backup'
  encoding: 'UTF-8'
  bom: false
  scheduleTime: '02:00'
  dateDepth: 1

monitorCache:
  directory: 'D:\Monitor'
  updateInterval: '00:01:30'

assort:
  - target: ROOM1

  - target: ROOM2

monitor:
  - target: ROOM1
...